### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by aboharbf** [rohankishore/Youtility#8]
Initialized a Conda environment with Python 3.11 (you should put the req'd version somewhere, I ran into a bunch of issues doing 3.10). Installed the reqs, opened the folder in vs code. Either hitting play on the main.py or putting python main.py triggers 

`'QWidget: Must construct a QApplication before a QWidget'. `

Doing the recommended python -m main.py gets me:
`
C:\Users\XXX\anaconda3\envs\yt\python.exe: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.`

Doing as recommended (python -m main) gets me the same as the first error.

**Comment by douglaskdonaldson** [comment]
Same issue installing in a fresh 3.10 pyenv virtualenv. I pulled today's change to `requirements.txt` and experienced exactly the same error from a fresh install.

I tried in VS Code and via `python -m main` after a successful installation.

**Comment by rohankishore** [comment]
Damn this's happening to a lot of users huh. I think it might be the import statements:
```python
from downloader import YoutubeVideo
from settings import SettingsPage
from playlist import YoutubePlaylist
from get_captions import CaptionWidget
```
since I'm directly importing the QWidgets. I'll update the code to not directly import the QWidgets (although it's running just fine in my PC)

**Comment by aboharbf** [comment]
Continuing here from the comment on the latest push. 
Commenting out the 'super().__init__()' gets me 'super-class __init__() of type Window was never called' on the fxn call right after (self.setTitleBar(CustomTitleBar(self))). 
![image](https://github.com/rohankishore/Youtility/assets/25850560/99999102-5c6f-43fe-be50-e9c58725b801)
